name: Test Package
on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12.5

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install scikit-image
        pip install -e .

    - name: Test with pytest
      run: |
        pytest